apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
