apiVersion: v1
kind: Service
metadata:
  name: shoopinggateway
spec:
  # nodeSelector:
  #   roll: worker
  type: LoadBalancer
  selector:
    app: shoopinggateway
  ports:
  - port: 3000
    targetPort: 81
