apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        roll: worker
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodata
          mountPath: /data/db
        - name: mongoconfig
          mountPath: /data/configdb
      volumes:
      - name: mongodata
        persistentVolumeClaim:
          claimName: mongodata-pvc
      - name: mongoconfig
        persistentVolumeClaim:
          claimName: mongoconfig-pvc
