apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongoconfig-pvc
spec:
  # nodeSelector:
  #   roll: worker
  storageClassName: local-storage1
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
