apiVersion: v1
kind: Service
metadata:
  name: shoopingproduct
spec:
  # nodeSelector:
  #   roll: worker
  type: ClusterIP
  selector:
    app: shoopingproduct
  ports:
  - port: 80
    targetPort: 80
