apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shoopinguser
spec:
  # nodeSelector:
  #   roll: worker
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoopinguser
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
